#!/bin/bash -

# Source the script
. bashme

# Basic settings
loglevel=$LL_INFO
log2file=1


# setterm --term linux --back green --fore black --clear all
TODO "Check for 'setterm'."

# Setup:
PROGRAM_NAME="${BOLD}Bash me${RESET}"
VERSION="${FG_GREEN}v0.1${RESET}"
YEAR=2018
FULL_NAME="Raphael Emberger"
LICENCE=$(cat LICENSE)
EXPLANATION='Provides nice features for bash scripting.'
USAGE=(
  '[OPTION]...    Execute script with arguments.'
  '               Show this help page.'
)
define_opt '_log'  '-l' ''         'n'    "Log level ${ITALIC}n${RESET}."
define_opt '_help' '-h' '--help'   ''     'Display this help text.'
define_opt '_ver'  '-v' ''         ''     'Display the VERSION.'
define_opt '_file' ''   '--output' 'file' "Write log to ${ITALIC}file${RESET}(defaults to $logfile)."
DESCRIPTION="
This is an example configuration to use the Bash-me script.
You can add a licence if you want."

# Parse arguments
parse_args "$@"

# Process options
[[ -n "$_help" ]] || [[ -z ${BASH_ARGC[@]} ]] && print_usage && exit
[[ -n "$_log" ]] && loglevel="$_log"
[[ -n "$_ver" ]] && print_version && exit
[[ -n "$_file" ]] && logfile="$_file"
[[ -n "${args[@]}" ]] && IFS=";" && info "Provided additional arguments: '${args[*]}'"

# Create a lock file
lock

# Setup traps
sig_err() {
  unlock
  error "Well, I guess something went wrong."
  exit;
}
sig_int() {
  unlock
  error "Bye bye."
  exit;
}
sig_exit() {
  unlock
}
trap_signals

# ... Code ...
loglevel=$LL_TRACE


#dialog --title 'Message' --msgbox 'Hello, world!' 5 20
info 'hi there!'
unlock